name: "Append Github PR Revision to description"
description: "Append the provided revision URL to Github pull request description"
branding:
  icon: "align-left"
  color: "blue"
inputs:
  auth:
    description: "The github auth token"
    required: true
  repo:
    description: "The github repo name"
    required: true
  owner:
    description: "The github repo owner"
    required: true
  pr:
    description: "The pr number"
    required: true
  url:
    description: "The output deployed url"
    required: true
  packageName:
    description: "The output package"
    required: true
  revision:
    description: "The output short commit SHA"
    required: true

runs:
  using: 'node16'
  main: 'index.js'